### PR TITLE
Pathway to ClientRequest

### PR DESCRIPTION
**Pull request by mayank-del**
## ✔️ Check List (Check all the applicable boxes) 

- [ x] My code follows the code style of this project.
- [ x] This PR does not contain plagiarized content.
- [x ] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

@KaizenGirl1111  maam, I connected WorkerLogin , WorkerSignup to backend  and I made signup page to navigate to login and then after worker will login , He will render to clientrequest page , Is Idea is ok or not ?

### CODE REVIEW

**Comment by KaizenGirl1111** [comment]
@mayank-del bro could you please fix the merge conflicts? Will review it asap

**Comment by ayush25102001** [comment]
> @mayank-del bro could you please fix the merge conflicts? Will review it asap

Mam these things of workerforms connection to backend are already done through the latest PR and I had also created the issue earlier

**Comment by mayank-del** [comment]
> @mayank-del bro could you please fix the merge conflicts? Will review it asap

Sorry for little delay, I solved the conflicts

**Review by KaizenGirl1111 — APPROVED** [review]

**Comment by mayank-del** [comment]
@KaizenGirl1111  maam ,conflicts resolved

**Comment by mayank-del** [comment]
@KaizenGirl1111 , maam check it .

**Comment by KaizenGirl1111** [comment]
> @KaizenGirl1111 , maam check it .

Mayank @mayank-del please check for merge conflicts

**Comment by mayank-del** [comment]
@KaizenGirl1111  maam , no merge it

**Review by KaizenGirl1111 — APPROVED** [review]

**Comment by mayank-del** [comment]
@KaizenGirl1111  maam actually problem was that Whenever  you merge any PR before my PR , it happens

**Comment by mayank-del** [comment]
@KaizenGirl1111 maam, Should I work more on your website, by arising new issues?

**Comment by KaizenGirl1111** [comment]
> @KaizenGirl1111  maam actually problem was that Whenever  you merge any PR before my PR , it happens

Yes , got it :")

**Comment by KaizenGirl1111** [comment]
> @KaizenGirl1111 maam, Should I work more on your website, by arising new issues?

You can check the recent website 
And work on a functionality you think is missing 
Or,
There are still some open issues 
Please check them

**Comment by Siddhesh777** [comment]
@KaizenGirl1111 
There are many errors in this PR.
@mayank-del has commented all the states variables too.
All the connections between frontend and backed got broken due to this PR.(The connection was established using fetch ,there was no need to reconnect them using axios. Moreover this is done incorrectly)
The project is not even starting in localhost.It is throwing many errors from different files.
@KaizenGirl1111  Please do check the changes before merging PRs.
Please remove this commit from the project.

**Comment by KaizenGirl1111** [comment]
Hey @mayank-del   did you comment out the recent changes made by other developers 🥲
Please understand they've worked on the project for long and this is not the way to make a PR get merged!

**Comment by mayank-del** [comment]
> Hey @mayank-del did you comment out the recent changes made by other developers 🥲 Please understand they've worked on the project for long and this is not the way to make a PR get merge.

No maam in your website , i added some functionalities, there were not any connection between frontend to backend

**Comment by mayank-del** [comment]
@ayush25102001  , if you are facing any issue just because of my PR , then feel free to connect with me in discord

**Comment by mayank-del** [comment]
@ayush25102001 , are you there??

**Comment by ayush25102001** [comment]
Yep

> @ayush25102001 , are you there??

Yep

**Comment by ayush25102001** [comment]
> @ayush25102001 , are you there??

Yep

**Comment by mayank-del** [comment]
> > @ayush25102001 , if you are facing any issue just because of my PR , then feel free to connect with me in discord
> > @ayush25102001 , give me your discord id, I checked it many times, let me what you are doing and what error you are getting
> 
> > 
> 
> Hi, the frontend to backend parts are already done please see check by sending data to forms and checks the entries locally in Robo3T

@ayush25102001 just see what changes I made , iI commented few variables to add new variables ,only declaration of variables were not creations.

**Comment by mayank-del** [comment]
> > @ayush25102001 , are you there??
> 
> Yep

Then ,come on discord , if you are having any issue , then tell me ,I am also watching, please dont make maam panic,  just thing about her.

**Comment by mayank-del** [comment]
@KaizenGirl1111  maam , please trust me , i am correct 

> Hey @mayank-del did you comment out the recent changes made by other developers 🥲 Please understand they've worked on the project for long and this is not the way to make a PR get merged!

Maam please trust me , I am correct , he might be confused due to his system issues, it still starting perfectly in my system, if you will say I will upload working video

**Comment by KaizenGirl1111** [comment]
hey sorry for the commotion @ayush25102001 @Siddhesh777 , I uncommitted the current commit, for now, please check if the website is working in the previous state. Also @mayank-del I understand this must be unintentional please check other issues and try to work on them without making changes to other contributors' code without their permission. Peace, wasn't a very big issue, have a good night guys

**Comment by mayank-del** [comment]
@KaizenGirl1111  maam, those developers are cheating you, they haven't linked frontend to backend yet , you can see on file changed what changes I did  , they are just playing with my hardwork, If he is true , then why not he is coming to discord, such things are easy maam , trust me maam, he is himself confused , just because of 1 developer , how you can think like that.
Don't be panic maam , I will never let trust down.

**Comment by ayush25102001** [comment]
Any updates @KaizenGirl1111 man

**Comment by mayank-del** [comment]
@ayush25102001 , can you tell me one thing , you had created frontend to backend worker login signup join or front and backend worker login signup??

**Comment by ayush25102001** [comment]
> @ayush25102001 , can you tell me one thing , you had created frontend to backend worker login signup join or front and backend worker login signup??

Run the project and check

**Comment by KaizenGirl1111** [comment]
> > I'll check the website again tomorrow, And don't worry I won't let anyone's score go down @mayank-del . Till now, there has been improvement into the site by all the contributors effort
> 
> Thank you maam, actually, ayush got confused in mongoose database , there you can see big code is commented , actually that was my written code😂😂 , i wrote that code for my practice, but it was having some issue, so i commented it and restored your code but I forgot to delete my commented code, so he thought that I commented big codes ,but that was mine, you can delete that commented code anytime.
- 
Ok @mayank-del I see what happened there, so it was your comment

**Comment by KaizenGirl1111** [comment]
I had uncommitted the last commit, so is the issue still persisting Ayush?

**Comment by mayank-del** [comment]
> I had uncommitted the last commit, so is the issue still persisting Ayush?



> > > I'll check the website again tomorrow, And don't worry I won't let anyone's score go down @mayank-del . Till now, there has been improvement into the site by all the contributors effort
> > 
> > 
> > Thank you maam, actually, ayush got confused in mongoose database , there you can see big code is commented , actually that was my written code😂😂 , i wrote that code for my practice, but it was having some issue, so i commented it and restored your code but I forgot to delete my commented code, so he thought that I commented big codes ,but that was mine, you can delete that commented code anytime.
> 
> 
> Ok @mayank-del I see what happened there, so it was your comment

@KaizenGirl1111  Maam, let me clear the confusion,
 I am listing everything whatever I did,

First bug was that in 



> > > I'll check the website again tomorrow, And don't worry I won't let anyone's score go down @mayank-del . Till now, there has been improvement into the site by all the contributors effort
> > 
> > 
> > Thank you maam, actually, ayush got confused in mongoose database , there you can see big code is commented , actually that was my written code😂😂 , i wrote that code for my practice, but it was having some issue, so i commented it and restored your code but I forgot to delete my commented code, so he thought that I commented big codes ,but that was mine, you can delete that commented code anytime.
> 
> 
> Ok @mayank-del I see what happened there, so it was your comment

No, maam,
I just want to say that he misunderstood my code.

Let me tell  you everything that i have done in this PR

First of all,  in your  worker.js , where schema is present , you can see category attribute was there, which i commented . Now, I commented that attribute just because of the fact that you are taking email from  frontend and storing it in in category array, email is not an array attribute and email is single item ,name was also invalid and format was also not correct.If you will do frontend to backend connection , it will give you a huge list of errors. I corrected it and added proper email attribute there instead of category array.
Then i made frontend to backend connection which was not present on your repo, then i make it navigate to login page connected to backend and after login ,i made it to navigate to client request page,  so that , if you want to add any more page ,you can add in between login and client request page.
I can only make client request page ,without touching your backend rest api ,but maam ,very honestly I am saying ,it would not  work , if someone would try to connect it, it would give him errors , whatever i am saying ,I have proper proves with me, you can verify by yourself , I haven't done anything to for gaining extra points maam, I did these extra backend frontend fixes ,just because of the fact that I know you are giving 45 points to everyone and for me those points really matters , so I thought to clear some extra bugs and add backend -frontend connections but  if helping someone by doing extra labour will return such type of responses , it really hurt me.

**Comment by mayank-del** [comment]
> > I had uncommitted the last commit, so is the issue still persisting Ayush?
> 
> > > > I'll check the website again tomorrow, And don't worry I won't let anyone's score go down @mayank-del . Till now, there has been improvement into the site by all the contributors effort
> > > 
> > > 
> > > Thank you maam, actually, ayush got confused in mongoose database , there you can see big code is commented , actually that was my written code😂😂 , i wrote that code for my practice, but it was having some issue, so i commented it and restored your code but I forgot to delete my commented code, so he thought that I commented big codes ,but that was mine, you can delete that commented code anytime.
> > 
> > 
> > Ok @mayank-del I see what happened there, so it was your comment
> 
> > > > I'll check the website again tomorrow, And don't worry I won't let anyone's score go down @mayank-del . Till now, there has been improvement into the site by all the contributors effort
> > > 
> > > 
> > > Thank you maam, actually, ayush got confused in mongoose database , there you can see big code is commented , actually that was my written code😂😂 , i wrote that code for my practice, but it was having some issue, so i commented it and restored your code but I forgot to delete my commented code, so he thought that I commented big codes ,but that was mine, you can delete that commented code anytime.
> > 
> > 
> > Ok @mayank-del I see what happened there, so it was your comment
> 
> No, maam, I just want to say that he misunderstood my code.
> 
> Let me tell you everything that i have done in this PR
> 
> First of all, in your worker.js , where schema is present , you can see category attribute was there, which i commented . Now, I commented that attribute just because of the fact that you are taking email from frontend and storing it in in category array, email is not an array attribute and email is single item ,name was also invalid and format was also not correct.If you will do frontend to backend connection , it will give you a huge list of errors. I corrected it and added proper email attribute there instead of category array. Then i made frontend to backend connection which was not present on your repo, then i make it navigate to login page and connected it to backend and after login ,i made it to navigate to client request page, so that , if you want to add any more page ,you can add in between login and client request page. I can only make client request page ,without touching your backend rest api ,but maam ,very honestly I am saying ,it would not work , if someone would try to connect it, it would give him errors , whatever i am saying ,I have proper proves with me, you can verify by yourself , I haven't done anything to for gaining extra points maam, I did these extra backend frontend fixes because I thought to clear some extra bugs and add backend -frontend connections just for you help but if helping someone by doing extra labour will return such type of responses , it really hurt me.

**Pull request merged**
