### PR TITLE
Show/hide password functionality added

### PR DESCRIPTION
**Pull request by Siddhesh777**
## 🛠️ Fixes Issue
Closes #31 

## 👨‍💻 Changes proposed
Added Show/hide password functionality which toggles the visibility of the password.

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by Siddhesh777** [comment]
hey @KaizenGirl1111 
Can you please review this PR

**Comment by KaizenGirl1111** [comment]
@Siddhesh777 this merge request has some conflicts. You can get it checked from @moulikagrawal mentor

**Comment by Siddhesh777** [comment]
@KaizenGirl1111 
Give me 5 min.
I will resolve it.

**Review by moulikagrawal — APPROVED** [review]
Looks fine, great job! @Siddhesh777

**Review by KaizenGirl1111 — APPROVED** [review]
Now it'll merge without any conflicts I believe. 
Good work!

**Pull request merged**
