### PR TITLE
signup with google fixed and added

### LINKED ISSUE #158: sign up using google for worker signup
**Is your feature request related to a problem? Please describe.**
Currently there is no sign up using google for worker signup . It is only there for user sign up.

**Describe the solution you'd like**
I would like to add sign up using google feature for worker sign up

Please assign me this issue under GSSoC'22.

### PR DESCRIPTION
**Pull request by piyusha2001**
## 👨‍💻 Changes proposed

While adding functionality of sign up using google to worker sign up i noticed sign up using google was not working for user sign up . So i first fixed that and then added sign up using google feature to workers sign up . Do check the working video below.

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots

Video-

https://user-images.githubusercontent.com/81703477/170824795-62058196-d3d5-4fed-8fb1-ee5771abb8ad.mp4

### CODE REVIEW

**Comment by piyusha2001** [comment]
@KaizenGirl1111  please review the PR and merge mine first as I have made some important changes..otherwise it may cause merge conflicts that will take time to resolve.

**Comment by piyusha2001** [comment]
@KaizenGirl1111  this was level 3 issue . Please check the tag in issues once .

**Comment by piyusha2001** [comment]
> @KaizenGirl1111 this was level 3 issue . Please check the tag in issues once - #158

**Comment by KaizenGirl1111** [comment]
Yes Piyusha. Thank you for reminding

**Pull request merged**
