### PR TITLE
NavigationBar and Footer added in Login Page

### LINKED ISSUE #39: Add Navbar and Footer in Login Page.
**Is your feature request related to a problem? Please describe.**

If the user move to login page then there is no button to go anywhere . The Login page looks like disconnected with the project.
For that reason I would like to add Navigation Bar and also footer in the Login Page.

It will look something like this 👇🏻

##Screenshot

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
I am contributor at gssoc'22.
Please assign this issue to me.

### PR DESCRIPTION
**Pull request by Siddhesh777**
## 🛠️ Fixes Issue

Closes #39 

## 👨‍💻 Changes proposed
Added Navigation Bar and Footer in Login Page.

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by Siddhesh777** [comment]
hey @KaizenGirl1111 
Can you please review this PR

**Comment by Siddhesh777** [comment]
hey @KaizenGirl1111 
I have removed the conflicts
Can you please review this once.

**Comment by KaizenGirl1111** [comment]
@Siddhesh777 this still appears to have some branch conflicts 
@moulikagrawal may help you

**Comment by Siddhesh777** [comment]
hey @KaizenGirl1111 
I will be doing it right now !

**Comment by Siddhesh777** [comment]
hey @KaizenGirl1111 
Conflicts Resolved

**Pull request merged**
