### PR TITLE
ModelAdded

### PR DESCRIPTION
**Pull request by ayush25102001**
## 🛠️ Fixes Issue
PR fixe issue #22 
## 👨‍💻 Changes proposed

I have created a userModel

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

>

### CODE REVIEW

**Comment by ayush25102001** [comment]
Please review @KaizenGirl1111

**Comment by ayush25102001** [comment]
Please review @KaizenGirl1111 sir

**Comment by ayush25102001** [comment]
Please review the PR @KaizenGirl1111

**Comment by KaizenGirl1111** [comment]
@ayush25102001 truly great work! I did review it in entirety.  
Keep it up :)

**Comment by ayush25102001** [comment]
@KaizenGirl1111 mam tags ??

**Comment by ayush25102001** [comment]
> @ayush25102001 truly great work! I did review it in entirety. Keep it up :)

Please add the Gssoc and the Level labels

**Comment by ayush25102001** [comment]
Please add labels @KaizenGirl1111

**Pull request merged**
