### PR TITLE
Reset Password page added

### LINKED ISSUE #159: Creating new Page for new password(after forgot password)
After forgot password ,user will get a reset-link which on clicked should take the user to change the password.I would like to make this page.I am contributor at GSSOC'22.
Please assign this issue to me.

### PR DESCRIPTION
**Pull request by Siddhesh777**
## 🛠️ Fixes Issue

Closes #159 

## 👨‍💻 Changes proposed
After forgot password ,user will get a reset-link which on clicked should take the user to change the password.I have made this page

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by Siddhesh777** [comment]
@KaizenGirl1111

**Comment by Siddhesh777** [comment]
@KaizenGirl1111 
Any changes required?

**Comment by Siddhesh777** [comment]
@KaizenGirl1111 
:(

**Comment by KaizenGirl1111** [comment]
No Siddesh, reset password looks good. 
Sorry when you put PR, I was in flight 😅

**Review by KaizenGirl1111 — APPROVED** [review]

**Pull request merged**
