### PR TITLE
Enhanced signin/signup UI

### PR DESCRIPTION
**Pull request by piyusha2001**
## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots

Screenshot 2022-05-24 235740
Screenshot 2022-05-24 235800
Screenshot 2022-05-24 235816
Screenshot 2022-05-24 235833

### CODE REVIEW

**Comment by KaizenGirl1111** [comment]
@piyusha2001 could you please check if your branch is upto date to the current codebase 
If it is then I'll merge it.
Thank you for this it looks a very good UI

**Comment by piyusha2001** [comment]
> @piyusha2001 could you please check if your branch is upto date to the current codebase If it is then I'll merge it. Thank you for this it looks a very good UI

Thankyou so much! Yes it is upto date with current codebase

**Comment by piyusha2001** [comment]
Hey @KaizenGirl1111  please review my PR.

**Comment by KaizenGirl1111** [comment]
Hi piyusha, it has some merge conflicts due to previous prs by contributors
Update the branch, I'll firstly merge your PR

**Comment by piyusha2001** [comment]
> Hi piyusha, it has some merge conflicts due to previous prs by contributors Update the branch, I'll firstly merge your PR

Okay

**Comment by piyusha2001** [comment]
@KaizenGirl1111  hey can u guide me a little? How can i resolve merge conflicts?

**Comment by piyusha2001** [comment]
I fetched upstream but it is not working...i think i am doing something wrong

**Comment by KaizenGirl1111** [comment]
@moulikagrawal please help Piyusha in fixing her merge conflicts

**Comment by piyusha2001** [comment]
@moulikagrawal can we have a meet or something? It will be easier to solve this issue that way.

**Comment by moulikagrawal** [comment]
> @moulikagrawal can we have a google meet or something? It will be easier to solve this issue that way.

@piyusha2001 sure, let's have a meet at 2:30 pm today, send me your email id so that i can share the link

**Comment by piyusha2001** [comment]
> > @moulikagrawal can we have a google meet or something? It will be easier to solve this issue that way.
> 
> @piyusha2001 sure, let's have a meet at 2:30 pm today, send me your email id so that i can share the link

Thank you so much ! My email id is - ppiyusha2001@gmail.com

**Comment by piyusha2001** [comment]
@KaizenGirl1111 Heyy I checked the conflicts and resolved them . Also ran the app to check the working and its working right. This PR is good to merge.

**Comment by KaizenGirl1111** [comment]
@piyusha2001 as you really worked hard on this PR, will give ur level 3 ^_^
Hope to see more of your contributions

**Comment by piyusha2001** [comment]
> @piyusha2001 as you really worked hard on this PR, will give ur level 3 ^_^ Hope to see more of your contributions

Thank you so much!! <3 . Do check new issue i created . I would like to work on that.

**Pull request merged**
