### PR TITLE
added Google Authentication

### LINKED ISSUE #97: Want to Setup Google Authentication
**Is your feature request related to a problem? Please describe.**

Want to add Google Authentication

@KaizenGirl1111 Please assign the task to me

### PR DESCRIPTION
**Pull request by Abh1shekSingh**
## 🛠️ Fixes Issue

Closes #97 

## 👨‍💻 Changes proposed

Added Google Authentication on Sign Up Page

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

I have added Google Authentication on Signup Page only and will add on login Page by creating new issue and PR. 

## 📷 Screenshots

sample
success

### CODE REVIEW

**Comment by Abh1shekSingh** [comment]
@KaizenGirl1111 Please review My PR

**Comment by KaizenGirl1111** [comment]
@Abh1shekSingh this looks so 🔥 lit 
Thanks for this
This pr has some merge conflicts, kindly correct them and I'll merge it asap

**Comment by Abh1shekSingh** [comment]
@KaizenGirl1111 Okay I will make New PR, becaause I dont know how could I fix these errors

**Comment by Abh1shekSingh** [comment]
@KaizenGirl1111 I did here only, Finally, Resolved the conflicts

**Comment by KaizenGirl1111** [comment]
> @KaizenGirl1111 I did here only, Finally, Resolved the conflicts

Thanks great

**Pull request merged**
