### PR TITLE
Error, warning messages got displayed

### LINKED ISSUE #186: Displaying proper error messages in login and signup page.
Proper error, success, warning messages (toast)should be displayed to the user if any error occurs.
I would like to contribute in this issue.Please assign this task to me.

I am contributor at GSSOC'22.
Please assign this issue to me.

### PR DESCRIPTION
**Pull request by Siddhesh777**
## 🛠️ Fixes Issue

Closes #186 

## 👨‍💻 Changes proposed
Added proper messages of warnings and errors to the user after login and signup

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by KaizenGirl1111** [comment]
Hi, few conflicts in the pr 
Will merge post resolving 🤟

**Comment by KaizenGirl1111** [comment]
Other PRs of today also have few conflicts @Siddhesh777 .
I will merge post dat ^_^

**Comment by Siddhesh777** [comment]
@KaizenGirl1111 
Done

**Comment by Siddhesh777** [comment]
@KaizenGirl1111 
Please review it asap.
I want to make some more PRs.
It will again create conflicts else

**Review by KaizenGirl1111 — APPROVED** [review]

**Comment by Siddhesh777** [comment]
@KaizenGirl1111 
labels please

**Pull request merged**
