### PR TITLE
WorkerFormEnabled

### PR DESCRIPTION
**Pull request by ayush25102001**
## 🛠️ Fixes Issue #96 

Just like User, the worker details are also stored in the database from the sign-up form now

- My code follows the code style of this project.
- This PR does not contain plagiarized content.
- The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by KaizenGirl1111** [comment]
@ayush25102001 this pr has some merge conflicts

**Comment by ayush25102001** [comment]
@KaizenGirl1111 mam conflicts are resolved

**Review by KaizenGirl1111 — APPROVED** [review]
Seems good now.
Thank you so much and all the very best

**Comment by KaizenGirl1111** [comment]
@ayush25102001 yes I get it 
Sorry, won't happen again

**Pull request merged**
