### PR TITLE
New user and Already registered button added in login and signup page

### LINKED ISSUE #46: "Already registered ?" button in signup page which takes the user to login page and "New User" button in login page
**Is your feature request related to a problem? Please describe.**
There should be `New User ?` button in login page which takes the user to register page in case the user has not registered himself.
There should be also `Already registered ?` button inside signup page which takes the user to the login page.
consequently there is no need to put a `signup` button inside navbar.

I would like to make above changes.

**Additional context**
I am contributor at gssoc'22.
Please assign this issue to me.

### PR DESCRIPTION
**Pull request by Siddhesh777**
## 🛠️ Fixes Issue

Closes #46 

## 👨‍💻 Changes proposed
Added `New user ?` and `Already registered ?` buttons in login and signup page respectively

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by KaizenGirl1111** [comment]
Hello @Siddhesh777 
Great effort! Appericiable ! 
Though this has some merge conflicts 
Please ask your doubts from @moulikagrawal mentor if any

**Comment by KaizenGirl1111** [comment]
@Siddhesh777 due to your consistent PRs, I'd like to give you a shout out  on LinkedIn. 
Kindly add your LinkedIn link in comments or dm it  at discord. Thank you so much!

**Review by moulikagrawal — CHANGES_REQUESTED** [review]
Your branch has merge conflicts in the Login and Signup file, kindly sort it out. Ping me for any help.

**Comment by Siddhesh777** [comment]
hey @KaizenGirl1111 
I have removed the conflicts
Please review

**Review by moulikagrawal — APPROVED** [review]

**Comment by Siddhesh777** [comment]
hey @moulikagrawal 
Can't you merge this PR?
I think practicals of @KaizenGirl1111 are going on, so she is busy.

**Comment by moulikagrawal** [comment]
I can't merge without the @KaizenGirl1111 permission.

**Pull request merged**
