### PR TITLE
Remove non functional options from navbar

### PR DESCRIPTION
**Pull request by ayush25102001**
Fixes issue #65 

Screenshot (138)

### CODE REVIEW

**Comment by ayush25102001** [comment]
@KaizenGirl1111 mam can u review this

**Comment by KaizenGirl1111** [comment]
@ayush25102001 where do you plan to put those non functional links?
You may comment here the things you removed, so that if we ever need to build them, we'll have a reference.

**Comment by ayush25102001** [comment]
> @ayush25102001 where do you plan to put those non functional links?
> You may comment here the things you removed, so that if we ever need to build them, we'll have a reference.

@KaizenGirl1111 mam AboutUs,Services and review links are non functional and thus removed them for now to make the navbar clean

**Comment by KaizenGirl1111** [comment]
ok @ayush25102001

**Pull request merged**
