### PR TITLE
Worker-Frontend

### PR DESCRIPTION
**Pull request by ayush25102001**
PR for issue #33

1->Added the worker schema(Backend)

2->Added the signUp form for workers

Screenshot (119)

3->Added the login form the wokers

Screenshot (120)

4->Created the worker login and signUp options in navbar
Screenshot (118)

### CODE REVIEW

**Comment by ayush25102001** [comment]
Please review the PR @KaizenGirl1111

**Comment by KaizenGirl1111** [comment]
Sorry for reviewing late @ayush25102001 had few tests and practicals
Great work!!!

**Comment by KaizenGirl1111** [comment]
@ayush25102001 due to your consistent PRs, I'd like to give you a shout out  on LinkedIn. 
Kindly add your LinkedIn link in comments or dm it  at discord. Thank you so much!

**Review by moulikagrawal — COMMENTED** [review]
Great Job !

**Pull request merged**
