### PR TITLE
Workers got displayed in new Page

### LINKED ISSUE #114: Creating Services page which will display all the workers and their details.
**Is your feature request related to a problem? Please describe.**
I would like to make a Services page which will display all the workers.

**Additional context**
I am contributor at GSSOC'22.
Please assign this issue to me.

### PR DESCRIPTION
**Pull request by Siddhesh777**
## 🛠️ Fixes Issue

Closes #114 

## 👨‍💻 Changes proposed
Created a Page which displays all the Dummy data of workers

## ✔️ Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by KaizenGirl1111** [comment]
Hi Siddesh ⚡
I believe you've done ✔ some great work
Could you please fix the merge conflict

**Comment by KaizenGirl1111** [comment]
@Siddhesh777

**Comment by KaizenGirl1111** [comment]
Will add level 3 @Siddhesh777

**Comment by Siddhesh777** [comment]
hey @KaizenGirl1111 resolved the conflicts

**Comment by Siddhesh777** [comment]
and someone just messed up with the UI of original website I just checked it right now while resolving conflicts



dont worry, I will manage it

**Review by KaizenGirl1111 — APPROVED** [review]

**Comment by KaizenGirl1111** [comment]
> and someone just messed up with the UI of original website I just checked it right now while resolving conflicts
> 
> 
> 
> dont worry, I will manage it

@Siddhesh777 you can add a new issue as enhancement of UI, I'll assign it it you

**Comment by Siddhesh777** [comment]
hey @KaizenGirl1111 
Resolved again

**Review by KaizenGirl1111 — APPROVED** [review]
Thanks for re correcting the UI :")

**Pull request merged**
