### PR TITLE
Project Hosted in Vercel

### LINKED ISSUE #34: Github Pages not working
_Hey contributors! This is a good first issue. Or if you're tired making advanced commits, here's an easy issue to give you solace._

The Github Pages is active but not working
If you're able to host from your side, just make a pr to the read.me and append the link of the site on the read.me

### PR DESCRIPTION
**Pull request by gurjeetsinghvirdee**
## 🛠️ Fixes Issue

Closes #34 

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

Github pages have some issues, So I deployed this project on Vercel 
Deployed link: https://gsg-rih-sangini.vercel.app/
Maybe it suits with your username

## 📷 Screenshots

Screenshot (922)

### CODE REVIEW

**Review by gurjeetsinghvirdee — COMMENTED** [review]
Review PR @KaizenGirl1111

**Comment by KaizenGirl1111** [comment]
Amazing @gurjeetsinghvirdee 
Thank you so much this :)

**Comment by KaizenGirl1111** [comment]
Do we need to deploy it again after some changes?

**Comment by gurjeetsinghvirdee** [comment]
> Do we need to deploy it again after some changes?

Don't think so

**Comment by gurjeetsinghvirdee** [comment]
@KaizenGirl1111 if changes not reflect in your website plz drop a msg on your project channel

**Pull request merged**
