### PR TITLE
Review section Added

### PR DESCRIPTION
**Pull request by Abh1shekSingh**
## 🛠️ Fixes Issue

Closes: #118 

## 👨‍💻 Changes proposed

Added Sigle Review 

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by KaizenGirl1111** [comment]
@Abh1shekSingh some people were already working on Gmail authentication 
Did you check whether your pr is clashing or not?

**Comment by Abh1shekSingh** [comment]
Yes, but they haven't PR for a long time. I did first and before them. So
mine should be counted

**Comment by Abh1shekSingh** [comment]
They have created the issue,but never Made a aPR and also my request to
make Authentication is before them, so I think, I should be counted for the
same.

**Comment by Abh1shekSingh** [comment]
@KaizenGirl1111  Check kr lijiye please

**Pull request merged**
