### PR TITLE
styled-home-page

### LINKED ISSUE #10: Enhance existing home page
The existing home page of the site is plain. If you have worked well in CSS, you are free to enhance the professionalism and aesthetics of this page.

### PR DESCRIPTION
**Pull request by mayank-del**
## ✔️ Check List (Check all the applicable boxes) 

- [ x] My code follows the code style of this project.
- [x ] This PR does not contain plagiarized content.
- [x ] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

I styled navbar which was very old fashioned. I also  added animation on  servicesContainer section, so that if you scroll the page towardsservicesContainer page it will fade.

### CODE REVIEW

**Comment by mayank-del** [comment]
@KaizenGirl1111  maam, i have styled your scrollbar also and made it beautiful, please check these changes and inform me if you want anything more

**Comment by KaizenGirl1111** [comment]
@mayank-del I'm eager to see your work, though your branch has some merge conflicts. Could you please recheck it?

**Comment by mayank-del** [comment]
Actually maam you can check in your main repo also, actually, in your codes lines like <<<<<<<<<<<<main
Have been written and around 9-10 such things were present in both login as well as signup file , if I would not remove those unwanted lines they would never 
let the program run, that's why these conflicts are coming.

**Comment by mayank-del** [comment]
@KaizenGirl1111  mam, have you understood the problem?

you can check in files changed option also, what changes I made on login and signup.

**Comment by mayank-del** [comment]
> @KaizenGirl1111 mam, have you understood the problem?
> 
> you can check in files changed option also, what changes I made on login and signup.

@KaizenGirl1111  maam , try to understand, nime is very less , you can check , I haven't touch the codes  , I just removed those unwanted  non-programming characters which will not let the program to run.

So, please , @KaizenGirl1111 maam , merge it , so that I can finish your rest issues, those are time taking

**Comment by KaizenGirl1111** [comment]
@mayank-del hi Mayank 
I'm trying to merge it but it has few conflicts due to which the pr is not merging even though I want to
Are some some lined as you've described in signup and login that can be removed and there won't be any merge conflicts?

**Comment by mayank-del** [comment]
@KaizenGirl1111  maam sorry for inconvenience , conflicts resolved

**Pull request merged**
