### PR TITLE
GS Sos Page added

### LINKED ISSUE #161: GrihSangini SoS
A page called GrihSangini SoS for emergency service deliveries under 2 hours. Eg. Emergency car repairing.

Right now, just build the frontend of this page.

The web page should be connected to the navbar. 

Format of this page-

<relevant image eg. Image of lady worker>
<GrihSangini SoS button>
<description of SoS services- We delivery service like emergency car repairing, emergency maid service in 2 hours in your vicinity. Terms and conditions applied>

This issue will be alloted to someone who can design a webpage aesthetically. :)

### PR DESCRIPTION
**Pull request by Siddhesh777**
## 🛠️ Fixes Issue

Closes #161 

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by Siddhesh777** [comment]
@KaizenGirl1111 
Is this page fine?

**Comment by KaizenGirl1111** [comment]
hi @Siddhesh777 yes this looks good, just if possible to remove the emergency image. We can have a center aligned before the form with a paragraph describing what is GrihSangini SoS. (I have written on this PRs issue, the paragraph)

**Comment by Siddhesh777** [comment]
yes sure @KaizenGirl1111 
But the paragraph is not there in issue.
Can you please confirm it once?

**Comment by Siddhesh777** [comment]
Is it good @KaizenGirl1111 ?
Right now I have put Lorem ipsum text.We can modify it later.

**Pull request merged**
